* bootstrap: Fix typos on redirections.
Signed-off-by: Akim Demaille <akim@lrde.epita.fr>

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -48,7 +48,7 @@ if test -z "$PERL"; then
 fi
 
 if test -z "$PERL"; then
-	echo "Cannot find perl" 2>&1
+	echo "Cannot find perl" >&2
 	exit 1
 fi
 
@@ -72,12 +72,12 @@ eval $apiver_cmd
 
 # Sanity checks
 if test -z "$VERSION"; then
-	echo "Cannot find VERSION" 2>&1
+	echo "Cannot find VERSION" >&2
 	exit 1
 fi
 
 if test -z "$APIVERSION"; then
-	echo "Cannot find VERSION" 2>&1
+	echo "Cannot find VERSION" >&2
 	exit 1
 fi
 
@@ -108,7 +108,7 @@ dosubst ()
 
 # Create temporary replacement for lib/Automake/Config.pm
 dosubst automake-$APIVERSION/Automake/Config.in \
-        automake-$APIVERSION/Automake/Config.pm
+	automake-$APIVERSION/Automake/Config.pm
 
 # Create temporary replacement for aclocal
 dosubst aclocal.in aclocal.tmp
