* configure.ac: Require Perl 5.6. * lib/Automake/Config.in: Require Perl 5.6 (not done in lib/Automake/General.pm because it is shared with Autoconf), and use `our' instead of `use vars'. * aclocal.in (rel2abs): Remove. (scan_configure_dep): Use File::Spec->rel2abs instead.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2026,9 +2026,13 @@ if test -z "$PERL"; then
 echo "$as_me: error: perl not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
-$PERL -e 'require 5.005;' || {
-   { { echo "$as_me:$LINENO: error: perl 5.005 or better is required" >&5
-echo "$as_me: error: perl 5.005 or better is required" >&2;}
+$PERL -e 'require 5.006;' || {
+   { { echo "$as_me:$LINENO: error: perl 5.6 or better is required.  If you have several perl
+versions installed, select the one Automake should use using
+  ./configure PERL=/path/to/perl" >&5
+echo "$as_me: error: perl 5.6 or better is required.  If you have several perl
+versions installed, select the one Automake should use using
+  ./configure PERL=/path/to/perl" >&2;}
    { (exit 1); exit 1; }; }
 }
 
