* configure.ac: Actually require version 2.60 in the test for Autoconf, and recommend it in the error messages. * THANKS: Update. Report by Robert Swafford.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2341,9 +2341,9 @@ fi
 { echo "$as_me:$LINENO: result: $am_cv_autoconf_installed" >&5
 echo "${ECHO_T}$am_cv_autoconf_installed" >&6; }
 if test "$am_cv_autoconf_installed" = no; then
-  { { echo "$as_me:$LINENO: error: Autoconf 2.58 or better is required.
+  { { echo "$as_me:$LINENO: error: Autoconf 2.60 or better is required.
     Please make sure it is installed and in your PATH." >&5
-echo "$as_me: error: Autoconf 2.58 or better is required.
+echo "$as_me: error: Autoconf 2.60 or better is required.
     Please make sure it is installed and in your PATH." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -2383,7 +2383,7 @@ if test "${am_cv_autoconf_version+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   mkdir conftest
-echo 'AC''_PREREQ(2.58)' > conftest/conftest.ac
+echo 'AC''_PREREQ(2.60)' > conftest/conftest.ac
 if { echo "$as_me:$LINENO: cd conftest && eval $am_AUTOCONF -o /dev/null conftest.ac" >&5
    (cd conftest && eval $am_AUTOCONF -o /dev/null conftest.ac) >&5 2>&5
    ac_status=$?
@@ -2399,8 +2399,8 @@ fi
 { echo "$as_me:$LINENO: result: $am_cv_autoconf_version" >&5
 echo "${ECHO_T}$am_cv_autoconf_version" >&6; }
 if test "$am_cv_autoconf_version" = no; then
-  { { echo "$as_me:$LINENO: error: Autoconf 2.58 or better is required." >&5
-echo "$as_me: error: Autoconf 2.58 or better is required." >&2;}
+  { { echo "$as_me:$LINENO: error: Autoconf 2.60 or better is required." >&5
+echo "$as_me: error: Autoconf 2.60 or better is required." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
