* configure.in: Test for Autoconf >= 2.52. * tests/defs (needs_autoconf, has_autoconf): Delete definition. * tests/ansi3.test, tests/ansi5.test, tests/ccnoco.test, tests/cond4.test, tests/cond9.test, tests/cond16.test, tests/cond18.test, tests/cond19.test, tests/cond20.test, tests/confsub.test, tests/depcomp2.test, tests/depdist.test, tests/depend2.test, tests/dirname.test, tests/distname.test, tests/extra5.test, tests/install2.test, tests/lex3.test, tests/make.test, tests/nobase.test, tests/pr9.test, tests/pr87.test, tests/stamph2.test, tests/subdir5.test, tests/subdirbuiltsources.test, tests/subobj3.test, tests/subobj5.test, tests/subobj6.test, tests/substref.test, tests/target-cflags.test, tests/yacc4.test, tests/yacc7.test, tests/yaccvpath.test: Do not use $needs_autoconf.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1260,6 +1260,18 @@ echo "$as_me: error: perl 5.005 or better is required" >&2;}
    { (exit 1); exit 1; }; }
 }
 
+echo 'AC''_PREREQ(2.52)' > conftest.ac
+{ echo "$as_me:$LINENO: eval $AUTOCONF -o /dev/null conftest.ac" >&5
+   (eval $AUTOCONF -o /dev/null conftest.ac) >&5 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); } || {
+   { { echo "$as_me:1269: error: Autoconf 2.52 or better is required" >&5
+echo "$as_me: error: Autoconf 2.52 or better is required" >&2;}
+   { (exit 1); exit 1; }; }
+}
+rm conftest.ac
+
 ac_config_files="$ac_config_files automake"
 
 ac_config_files="$ac_config_files aclocal"
@@ -1374,7 +1386,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1377: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1389: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1542,7 +1554,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1545: error: ambiguous option: $1
+    { { echo "$as_me:1557: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1561,7 +1573,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1564: error: unrecognized option: $1
+  -*) { { echo "$as_me:1576: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1604,7 +1616,7 @@ do
   "lib/am/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/am/Makefile" ;;
   "m4/Makefile" ) CONFIG_FILES="$CONFIG_FILES m4/Makefile" ;;
   "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
-  *) { { echo "$as_me:1607: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1619: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1818,7 +1830,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1821: creating $ac_file" >&5
+    { echo "$as_me:1833: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1836,7 +1848,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1839: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1851: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1849,7 +1861,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1852: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1864: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
