* m4/missing.m4: Use eval, instead of a sub-shell, to test for --run support in the missing script, since SHELL is not exported. Reported by job bogan <job@piquin.uchicago.edu> * aclocal.m4, configure: Rebuilt.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -665,8 +665,18 @@ test "$program_suffix" != NONE &&
 # sed with no file args requires a program.
 test "$program_transform_name" = "" && program_transform_name="s,x,x,"
 
+
+test x"${MISSING+set}" = xset || \
+  MISSING="\${SHELL} $ac_aux_dir/missing"
+if eval "$MISSING --run :"; then
+  am_missing_run="$MISSING --run "
+else
+  am_missing_run=
+  echo "configure: warning: \`missing' script is too old or missing" 1>&2
+fi
+
 echo $ac_n "checking whether ${MAKE-make} sets \${MAKE}""... $ac_c" 1>&6
-echo "configure:670: checking whether ${MAKE-make} sets \${MAKE}" >&5
+echo "configure:680: checking whether ${MAKE-make} sets \${MAKE}" >&5
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_prog_make_${ac_make}_set'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -738,18 +748,29 @@ EOF
 
 
 
-missing_dir=`cd $ac_aux_dir && pwd`
-ACLOCAL=${ACLOCAL-"$missing_dir/missing --run aclocal"}
 
-AUTOCONF=${AUTOCONF-"$missing_dir/missing --run autoconf"}
 
-AUTOMAKE=${AUTOMAKE-"$missing_dir/missing --run automake"}
+ACLOCAL=${ACLOCAL-"${am_missing_run}aclocal"}
 
-AUTOHEADER=${AUTOHEADER-"$missing_dir/missing --run autoheader"}
 
-MAKEINFO=${MAKEINFO-"$missing_dir/missing --run makeinfo"}
 
-AMTAR=${AMTAR-"$missing_dir/missing --run tar"}
+AUTOCONF=${AUTOCONF-"${am_missing_run}autoconf"}
+
+
+
+AUTOMAKE=${AUTOMAKE-"${am_missing_run}automake"}
+
+
+
+AUTOHEADER=${AUTOHEADER-"${am_missing_run}autoheader"}
+
+
+
+MAKEINFO=${MAKEINFO-"${am_missing_run}makeinfo"}
+
+
+
+AMTAR=${AMTAR-"${am_missing_run}tar"}
 
 
 
@@ -759,11 +780,14 @@ AMTAR=${AMTAR-"$missing_dir/missing --run tar"}
 
    
 
+
+ACLOCAL="`pwd`/aclocal --acdir=m4"
+AUTOMAKE="`pwd`/automake --amdir=."
 
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:767: checking for $ac_word" >&5
+echo "configure:791: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PERL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
