disallow use of perl 5.001

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -824,8 +824,10 @@ else
 fi
 
 if test -z "$PERL"; then
-   echo "fatal error: perl not found" 1>&2
-   exit 1
+   { echo "configure: error: perl not found" 1>&2; exit 1; }
+fi
+if test -n "`$PERL -v | fgrep 'version 5.001' 2> /dev/null`"; then
+   { echo "configure: error: perl 5.001 has bug which causes automake to fail" 1>&2; exit 1; }
 fi
 
 trap '' 1 2 15
