Abort if perl not found

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -14,9 +14,11 @@ ALL_LINGUAS=
 AC_ARG_PROGRAM
 fp_PROG_INSTALL
 
-AC_PATH_PROG(PERL, perl,
-echo "Perl not found; aborting"
-exit 1)
+AC_PATH_PROG(PERL, perl)
+if test -z "$PERL"; then
+   echo "fatal error: perl not found" 1>&2
+   exit 1
+fi
 
 dnl
 dnl NLS configuration.
