* configure.in: Do not use missing while checking for Autoconf's version, otherwise we won't notice that Autoconf isn't installed. Augment the error message with a few questions to help users.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1230,6 +1230,11 @@ ac_config_sub="$SHELL $ac_aux_dir/config.sub"
 ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 
 
+# Save the AUTOCONF setting before AM_INIT_AUTOMAKE overrides it;
+# this way we can run Autoconf tests from configure without being
+# bothered by `missing'.
+am_AUTOCONF=${AUTOCONF-autoconf}
+
 am__api_version="1.7a"
 # Find a good install program.  We prefer a C program (faster),
 # so one script is as good as another.  But avoid the broken or
@@ -1707,13 +1712,17 @@ fi
 # autom4te.cache).
 mkdir conftest
 echo 'AC''_PREREQ(2.54)' > conftest/conftest.ac
-{ echo "$as_me:$LINENO: cd conftest && eval $AUTOCONF -o /dev/null conftest.ac" >&5
-   (cd conftest && eval $AUTOCONF -o /dev/null conftest.ac) >&5 2>&5
+{ echo "$as_me:$LINENO: cd conftest && eval $am_AUTOCONF -o /dev/null conftest.ac" >&5
+   (cd conftest && eval $am_AUTOCONF -o /dev/null conftest.ac) >&5 2>&5
    ac_status=$?
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } || {
-   { { echo "$as_me:$LINENO: error: Autoconf 2.54 or better is required" >&5
-echo "$as_me: error: Autoconf 2.54 or better is required" >&2;}
+   { { echo "$as_me:$LINENO: error: Autoconf 2.54 or better is required.
+  Is it installed?  Is it in your PATH?  (try running \`autoconf --version')
+  Is it working?  See also config.log for error messages before this one." >&5
+echo "$as_me: error: Autoconf 2.54 or better is required.
+  Is it installed?  Is it in your PATH?  (try running \`autoconf --version')
+  Is it working?  See also config.log for error messages before this one." >&2;}
    { (exit 1); exit 1; }; }
 }
 rm -rf conftest
