* configure.in: Require Perl 5.005. 	* automake.in: Require 5.005.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -878,9 +878,9 @@ fi
 if test -z "$PERL"; then
    { echo "configure: error: perl not found" 1>&2; exit 1; }
 fi
-if test -n "`$PERL -v | fgrep 'version 5.001' 2> /dev/null`"; then
-   { echo "configure: error: perl 5.001 has bug which causes automake to fail" 1>&2; exit 1; }
-fi
+$PERL -e 'require 5.005;' || {
+   { echo "configure: error: perl 5.005 or better is required" 1>&2; exit 1; }
+}
 
 trap '' 1 2 15
 cat > confcache <<\EOF
