* configure.in: Really check for Autoconf 2.54.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1636,14 +1636,14 @@ echo "$as_me: error: perl 5.005 or better is required" >&2;}
 # deletion of any files created (such as those added to
 # autom4te.cache).
 mkdir conftest
-echo 'AC''_PREREQ(2.53b)' > conftest/conftest.ac
+echo 'AC''_PREREQ(2.54)' > conftest/conftest.ac
 { echo "$as_me:$LINENO: cd conftest && eval $AUTOCONF -o /dev/null conftest.ac" >&5
    (cd conftest && eval $AUTOCONF -o /dev/null conftest.ac) >&5 2>&5
    ac_status=$?
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); } || {
-   { { echo "$as_me:$LINENO: error: Autoconf 2.53b or better is required" >&5
-echo "$as_me: error: Autoconf 2.53b or better is required" >&2;}
+   { { echo "$as_me:$LINENO: error: Autoconf 2.54 or better is required" >&5
+echo "$as_me: error: Autoconf 2.54 or better is required" >&2;}
    { (exit 1); exit 1; }; }
 }
 rm -rf conftest
