Can't use 'true' in Makefiles

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -293,6 +293,10 @@ maintainer-clean: distclean maintainer-clean-binSCRIPTS maintainer-clean-vti mai
 # The simplest form of checking.
 check-local: automake
 	@PERL@ -c -w automake
+	if grep '^[^#].*true' *.am; then :; else \
+	  echo "can't use 'true' in GNU Makefile" 1>&2; \
+	  exit 1;				\
+	fi
 
 automake: automake.in
 	CONFIG_FILES=$@ CONFIG_HEADERS= ./config.status
