* Makefile.am (maintainer-clean): Disallow '$AUTOMAKE && exit 1'. Ignore @...@ substitutions in comments. * tests/defs.in: Try to make the shell more POSIX compliant. (AUTOMAKE_run, AUTOMAKE_fails): New functions. * tests/README: Mention AUTOMAKE_fails. * tests/alloca.test, tests/alloca2.test, tests/ansi8.test, * tests/asm.test, tests/backsl3.test, tests/backsl4.test, * tests/badline.test, tests/badopt.test, tests/canon.test, * tests/canon5.test, tests/colneq.test, tests/comment3.test, * tests/comment5.test, tests/cond2.test, tests/cond20.test, * tests/cond23.test, tests/cond24.test, tests/cond27.test, * tests/condinc2.test, tests/conff2.test, tests/cxx2.test, * tests/dejagnu2.test, tests/dirforbid.test, * tests/distcom3.test, tests/else.test, tests/exdir2.test, * tests/exeext2.test, tests/gcj2.test, tests/gcj5.test, * tests/getopt.test, tests/gettext.test, tests/gettext2.test, * tests/gnits.test, tests/gnuwarn.test, tests/gnuwarn2.test, * tests/insh.test, tests/lex2.test, tests/libobj10.test, * tests/libobj12.test, tests/libobj13.test, * tests/libobj3.test, tests/library2.test, * tests/library3.test, tests/libtool4.test, * tests/libtool6.test, tests/lisp2.test, tests/location.test, * tests/nogzip2.test, tests/output5.test, tests/overrid.test, * tests/percent.test, tests/percent2.test, * tests/pluseq5.test, tests/pluseq7.test, tests/pluseq9.test, * tests/pr211.test, tests/primary.test, tests/primary2.test, * tests/python2.test, tests/recurs.test, tests/reqd2.test, * tests/seenc.test, tests/specflg.test, tests/specflg2.test, * tests/spell.test, tests/spell2.test, tests/srcsub.test, * tests/srcsub2.test, tests/stdlib.test, tests/subdir7.test, * tests/substtarg.test, tests/suffix11.test, * tests/symlink.test, tests/syntax.test, * tests/targetclash.test, tests/txinfo4.test, * tests/version3.test, tests/warnopts.test, * tests/xsource.test, tests/yacc2.test: Use set -e, AUTOMAKE_fails, and always grep error message.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -190,6 +190,11 @@ maintainer-check: automake aclocal
 	  echo 'Do not run "automake" in the above tests.  Use "$$AUTOMAKE" instead.' 1>&2;  \
 	  exit 1; \
 	fi
+## Use AUTOMAKE_fails when appropriate
+	@if grep -v '^#' $(srcdir)/tests/*.test | grep '\$$AUTOMAKE.*&&.*exit'; then \
+	  echo 'Use AUTOMAKE_fails + grep to catch automake failures in the above tests.' 1>&2;  \
+	  exit 1; \
+	fi
 ## Tests should never call aclocal directly.
 	@if grep -v '^#' $(srcdir)/tests/*.test | grep ':[	]*aclocal'; then \
 	  echo 'Do not run "aclocal" in the above tests.  Use "$$ACLOCAL" instead.' 1>&2;  \
@@ -236,12 +241,11 @@ maintainer-check: automake aclocal
 	fi
 ## Try to make sure all @...@ substitutions are covered by our
 ## substitution rule.
-	@if test `grep -E '@[A-Za-z_0-9]+@' aclocal | wc -l` -ne 0; then \
+	@if test `grep -E '^[^#]*@[A-Za-z_0-9]+@' aclocal | wc -l` -ne 0; then \
 	  echo "Unresolved @...@ substitution in aclocal" 1>&2; \
 	  exit 1; \
 	fi
-## In automake there are a few valid ones.
-	@if test `grep -E '@[A-Za-z_0-9]+@' automake | wc -l` -ne 5; then \
+	@if test `grep -E '^[^#]*@[A-Za-z_0-9]+@' automake | wc -l` -ne 0; then \
 	  echo "Unresolved @...@ substitution in automake" 1>&2; \
 	  exit 1; \
 	fi
diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -584,7 +584,7 @@ distcheck: dist
 	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
 	$(am__remove_distdir)
 	@(echo "$(distdir) archives ready for distribution: "; \
-	  for i in $(DIST_ARCHIVES); do echo $$i; done) | \
+	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
 	  sed -e '1{h;s/./=/g;p;x}' -e '$${p;x}'
 distuninstallcheck:
 	@cd $(distuninstallcheck_dir) \
@@ -696,7 +696,7 @@ installcheck-am:
 
 maintainer-clean: maintainer-clean-recursive
 	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
-	-rm -rf autom4te.cache
+	-rm -rf $(top_srcdir)/autom4te.cache
 maintainer-clean-am: distclean-am maintainer-clean-aminfo \
 	maintainer-clean-generic maintainer-clean-vti
 
@@ -847,6 +847,10 @@ maintainer-check: automake aclocal
 	  echo 'Do not run "automake" in the above tests.  Use "$$AUTOMAKE" instead.' 1>&2;  \
 	  exit 1; \
 	fi
+	@if grep -v '^#' $(srcdir)/tests/*.test | grep '\$$AUTOMAKE.*&&.*exit'; then \
+	  echo 'Use AUTOMAKE_fails + grep to catch automake failures in the above tests.' 1>&2;  \
+	  exit 1; \
+	fi
 	@if grep -v '^#' $(srcdir)/tests/*.test | grep ':[	]*aclocal'; then \
 	  echo 'Do not run "aclocal" in the above tests.  Use "$$ACLOCAL" instead.' 1>&2;  \
 	  exit 1; \
@@ -882,11 +886,11 @@ maintainer-check: automake aclocal
 	  echo 'Do not use egrep or fgrep in the above files, they are not portable.' 1>&2; \
 	  exit 1; \
 	fi
-	@if test `grep -E '@[A-Za-z_0-9]+@' aclocal | wc -l` -ne 0; then \
+	@if test `grep -E '^[^#]*@[A-Za-z_0-9]+@' aclocal | wc -l` -ne 0; then \
 	  echo "Unresolved @...@ substitution in aclocal" 1>&2; \
 	  exit 1; \
 	fi
-	@if test `grep -E '@[A-Za-z_0-9]+@' automake | wc -l` -ne 5; then \
+	@if test `grep -E '^[^#]*@[A-Za-z_0-9]+@' automake | wc -l` -ne 0; then \
 	  echo "Unresolved @...@ substitution in automake" 1>&2; \
 	  exit 1; \
 	fi
diff --git a/tests/defs.in b/tests/defs.in
--- a/tests/defs.in
+++ b/tests/defs.in
@@ -22,6 +22,18 @@
 # Defines for Automake testing environment.
 # Tom Tromey <tromey@cygnus.com>
 
+# Be Bourne compatible.
+# (Snippet copied from configure's initialization in Autoconf 2.57.)
+if test -n "${ZSH_VERSION+set}" && (emulate sh) >/dev/null 2>&1; then
+  emulate sh
+  NULLCMD=:
+  # Zsh 3.x and 4.x performs word splitting on ${1+"$@"}, which
+  # is contrary to our usage.  Disable this feature.
+  alias -g '${1+"$@"}'='"$@"'
+elif test -n "${BASH_VERSION+set}" && (set -o posix) >/dev/null 2>&1; then
+  set -o posix
+fi
+
 # Ensure we are running from the right directory.
 test -f ./defs || {
    echo "defs: not found in current directory" 1>&2
@@ -296,6 +308,30 @@ sleep='sleep @MODIFICATION_DELAY@'
 # to override the definition from the Makefile.
 testsrcdir=$srcdir
 unset srcdir
+
+# AUTOMAKE_run status [options...]
+# --------------------------------
+# Run Automake with OPTIONS, and fail if automake
+# does not exit with STATUS.
+AUTOMAKE_run ()
+{
+  expected_exitcode=$1
+  shift
+  exitcode=0
+  $AUTOMAKE ${1+"$@"} 2>stderr >stdout || exitcode=$?
+  cat stderr
+  cat stdout
+  test $exitcode = $expected_exitcode || exit 1
+}
+
+# AUTOMAKE_fails [options...]
+# ---------------------------
+# Run Automake with OPTIONS, and fail if automake
+# does not exit with STATUS.
+AUTOMAKE_fails ()
+{
+  AUTOMAKE_run 1 ${1+"$@"}
+}
 
 # Turn on shell traces when VERBOSE=x.
 if test "x$VERBOSE" = xx; then
