* tests/missing.test, tests/missing2.test: Do not require GNUmake. * Makefile.am (maintainer-check): Make sure `required=' does not follow `. ./defs' in the tests.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -225,6 +225,13 @@ maintainer-check: automake aclocal
 	  echo 'Do not run "perl" in the above tests.  Use "$$PERL" instead.' 1>&2; \
 	  exit 1; \
 	fi
+## Setting `required' after sourcing `./defs' is a bug.
+	@for file in $(srcdir)/tests/*.test; do \
+	  if out=`sed -n '/defs/,$${/required=/p;}' $$file`; test -n "$$out"; then \
+	    echo 'Do not set "required" after sourcing "defs" in '"$$file: $$out" 1>&2; \
+	    exit 1; \
+	  fi; \
+	done
 ## Overriding a Makefile macro on the command line is not portable when
 ## recursive targets are used.  Better use an envvar.  SHELL is an exception,
 ## POSIX says it can't come from the environment.
diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -774,6 +774,12 @@ maintainer-check: automake aclocal
 	  echo 'Do not run "perl" in the above tests.  Use "$$PERL" instead.' 1>&2; \
 	  exit 1; \
 	fi
+	@for file in $(srcdir)/tests/*.test; do \
+	  if out=`sed -n '/defs/,$${/required=/p;}' $$file`; test -n "$$out"; then \
+	    echo 'Do not set "required" after sourcing "defs" in '"$$file: $$out" 1>&2; \
+	    exit 1; \
+	  fi; \
+	done
 	@if grep -E '\$$MAKE .*(SHELL=.*=|=.*SHELL=)' $(srcdir)/tests/*.test; then \
 	  echo 'Rewrite "$$MAKE foo=bar SHELL=$$SHELL" as "foo=bar $$MAKE -e SHELL=$$SHELL"' 1>&2; \
 	  echo ' in the above lines, it is more portable.' 1>&2; \
