runtest: support option --shell, tell which shell should run the test
* runtest.in: Here.  The same effect could have been obtained by
exporting AM_TEST_RUNNER_SHELL to the desired value, but the new
API is simpler and requires less typing and less thinking.

Signed-off-by: Stefano Lattarini <stefano.lattarini@gmail.com>

diff --git a/runtest.in b/runtest.in
--- a/runtest.in
+++ b/runtest.in
@@ -32,11 +32,19 @@ shell_opts=
 while test $# -gt 0; do
   case $1 in
     --help)
-       echo "Usage: $0 [SHELL-OPTIONS] TEST [TEST-OPTIONS]"
+       echo "Usage: $0 [--shell=PATH] [SHELL-OPTIONS] TEST [TEST-OPTIONS]"
        exit $?
        ;;
+    --shell)
+       test $# -gt 1 || error "missing argument for option '$1'"
+       AM_TEST_RUNNER_SHELL=$2
+       shift
+       ;;
+    --shell=*)
+       AM_TEST_RUNNER_SHELL=${1#--shell=}
+       ;;
     -o)
-       test $# -gt 1 || error "missing argument for option '-o'"
+       test $# -gt 1 || error "missing argument for option '$1'"
        shell_opts="-o $2"
        shift
        ;;
