Tests defs: $testsbuilddir is now AC_SUBST'ed.
* tests/defs.in ($testsbuilddir): Substitute from @abs_builddir@.
Add sanity check on $testsbuilddir, similar to those on
$testsrcdir and $top_testsrcdir.

diff --git a/tests/defs.in b/tests/defs.in
--- a/tests/defs.in
+++ b/tests/defs.in
@@ -28,6 +28,7 @@
 # Absolutely necessary variable(s).
 testsrcdir='@abs_srcdir@'
 top_testsrcdir='@abs_top_srcdir@'
+testbuilddir='@abs_builddir@'
 
 # Protect this file against multiple inclusion, useful for generated tests.
 if test x"$am_skip_defs" = xyes; then
@@ -99,9 +100,6 @@ sleep='sleep @MODIFICATION_DELAY@'
 # in UTC; see <http://www.gnu.org/gnu/initial-announcement.html>.
 old_timestamp=198309271735.59
 
-# Absolute path of the testsuite buildir.
-testbuilddir=`pwd`
-
 # Make our wrapper scripts accessible by default.
 PATH="$testbuilddir$PATH_SEPARATOR$PATH"; export PATH
 
@@ -119,6 +117,12 @@ test -f ./defs || {
 # Ensure $testsrcdir is set correctly.
 test -f "$testsrcdir/defs.in" || {
    echo "$me: $testsrcdir/defs.in not found, check \$testsrcdir" >&2
+   exit 1
+}
+
+# Ensure $testbuilddir is set correctly.
+test -f "$testbuilddir/defs" || {
+   echo "$me: $testbuilddir/defs not found, check \$testbuilddir" >&2
    exit 1
 }
 
