tests defs: more namespace-safeness
($using_tap): Renamed ...
($am_using_tap): ... to this.
($parallel_tests): Renamed ...
($am_parallel_tests): ... to this.
($test_prefer_config_shell): Renamed ...
($am_test_prefer_config_shell): ... to this.
($original_AUTOMAKE): Renamed ...
($am_original_AUTOMAKE): ... to this.
($original_ACLOCAL): Renamed ...
($am_original_ACLOCAL): ... to this.
* tests/defs, tests/defs-static.in, tests/gen-testsuite-part,
tests/README, and all callers: Adjusted.
* tests/Makefile.am (AM_TESTS_ENVIRONMENT): Adjust, and rewrite
to make future adjustments easier.
* tests/defs (funcs_file_): Renamed ...
(am_funcs_file): ... to this.
* Makefile.am (sc_tests_obsolete_variables): New maintainer
check.
(syntax_check_rules): Add it.

diff --git a/tests/defs b/tests/defs
--- a/tests/defs
+++ b/tests/defs
@@ -122,7 +122,7 @@ esac
 ## ----------------------- ##
 
 echo "Running from installcheck: $am_running_installcheck"
-echo "Using TAP: $using_tap"
+echo "Using TAP: $am_using_tap"
 echo "PATH = $PATH"
 
 
@@ -201,22 +201,22 @@ Exit ()
   (exit $1); exit $1
 }
 
-if test $using_tap = yes; then
-  funcs_file_=tap-functions.sh
+if test $am_using_tap = yes; then
+  am_funcs_file=tap-functions.sh
 else
-  funcs_file_=plain-functions.sh
+  am_funcs_file=plain-functions.sh
 fi
 
-if test -f "$testsrcdir/$funcs_file_"; then
-  . "$testsrcdir/$funcs_file_" || {
-    echo "$me: error sourcing $testsrcdir/$funcs_file_" >&2
+if test -f "$testsrcdir/$am_funcs_file"; then
+  . "$testsrcdir/$am_funcs_file" || {
+    echo "$me: error sourcing $testsrcdir/$am_funcs_file" >&2
     Exit 99
   }
 else
-  echo "$me: $testsrcdir/$funcs_file_ not found, check \$testsrcdir" >&2
+  echo "$me: $testsrcdir/$am_funcs_file not found, check \$testsrcdir" >&2
   Exit 99
 fi
-unset funcs_file_
+unset am_funcs_file
 
 # Avoid spurious TAP diagnostic.  Keep this in sync with the definition
 # of $(TAP_LOG_DRIVER_FLAGS) in `tests/Makefile.am'.
@@ -276,7 +276,7 @@ AUTOMAKE_run ()
   $AUTOMAKE ${1+"$@"} >stdout 2>stderr || am__got_rc=$?
   cat stderr >&2
   cat stdout
-  if test $using_tap != yes; then
+  if test $am_using_tap != yes; then
     test $am__got_rc -eq $am__exp_rc || Exit 1
     return
   fi
@@ -483,12 +483,12 @@ sed_unindent_prog="" # Avoid interferences from the environment.
 # get_shell_script SCRIPT-NAME
 # -----------------------------
 # Fetch an Automake-provided shell script from the `lib/' directory into
-# the current directory, and, if the `$test_prefer_config_shell' variable
-# is set to "yes", modify its shebang line to use $SHELL instead of
-# /bin/sh.
+# the current directory, and, if the `$am_test_prefer_config_shell'
+# variable is set to "yes", modify its shebang line to use $SHELL instead
+# of /bin/sh.
 get_shell_script ()
 {
-  if test x"$test_prefer_config_shell" = x"yes"; then
+  if test x"$am_test_prefer_config_shell" = x"yes"; then
     sed "1s|#!.*|#! $SHELL|" "$am_scriptdir/$1" > "$1"
     chmod a+x "$1"
   else
@@ -573,7 +573,7 @@ do
     xsi-bin-sh)
       require_xsi "/bin/sh";;
     xsi-lib-shell)
-      if test x"$test_prefer_config_shell" = x"yes"; then
+      if test x"$am_test_prefer_config_shell" = x"yes"; then
         require_xsi "$SHELL"
       else
         require_xsi "/bin/sh"
@@ -917,7 +917,7 @@ if test "$sh_errexit_works" = yes; then
     else
       keep_testdirs=no
     fi
-    if test $using_tap = yes; then
+    if test $am_using_tap = yes; then
       if test $have_tap_plan_ != yes && test $exit_status -eq 0; then
         plan_ "now"
       fi
@@ -976,7 +976,7 @@ else
     # to append AC_OUTPUT.
     {
       echo "AC_INIT([$me], [1.0])"
-      if test x"$parallel_tests" = x"yes"; then
+      if test x"$am_parallel_tests" = x"yes"; then
         echo "AM_INIT_AUTOMAKE([parallel-tests])"
       else
         echo "AM_INIT_AUTOMAKE"
