tests: move most helper scripts and files into the 'ax' subdirectory
* tests/defs-static.in ($am_testauxdir): New variable.
* tests/testsuite-summary-checks.sh: Moved ...
* tests/ax/testsuite-summary-checks.sh: ... here.
* tests/trivial-test-driver: Moved ...
* tests/ax/trivial-test-driver: ... here.
* tests/tap-summary-aux.sh: Moved ...
* tests/ax/tap-summary-aux.sh: ... here.
* tests/distcheck-hook-m4.am: Moved ...
* tests/ax/distcheck-hook-m4.am: ... here.
* tests/prove-runner: Moved ...
* tests/ax/prove-runner: ... here.
* tests/depcomp.sh: Moved ...
* tests/ax/depcomp.sh: ... here.
* tests/tap-setup.sh: Moved ...
* tests/ax/tap-setup.sh: ... here.
* tests/tap-functions.sh: Moved ...
* tests/ax/tap-functions.sh: ... here.
* tests/plain-functions.sh: Moved ...
* tests/ax/plain-functions.sh: ... here.
* tests/extract-testsuite-summary: Moved ...
* tests/ax/extract-testsuite-summary.pl: .. . here.
* tests/gen-testsuite-part: Adjusted accordingly.
* tests/Makefile.am: Likewise.
* tests/defs: Likewise.
* syntax-check.mk: Likewise.
* Several tests: Likewise.

Signed-off-by: Stefano Lattarini <stefano.lattarini@gmail.com>

diff --git a/tests/defs b/tests/defs
--- a/tests/defs
+++ b/tests/defs
@@ -217,13 +217,13 @@ else
   am_funcs_file=plain-functions.sh
 fi
 
-if test -f "$testsrcdir/$am_funcs_file"; then
-  . "$testsrcdir/$am_funcs_file" || {
+if test -f "$am_testauxdir/$am_funcs_file"; then
+  . "$am_testauxdir/$am_funcs_file" || {
     echo "$me: error sourcing $testsrcdir/$am_funcs_file" >&2
     Exit 99
   }
 else
-  echo "$me: $testsrcdir/$am_funcs_file not found, check \$testsrcdir" >&2
+  echo "$me: $am_testauxdir/$am_funcs_file not found" >&2
   Exit 99
 fi
 unset am_funcs_file
