Tests defs: use `$me' in more error messages.
* tests/defs.in: Also use `$me' in error messages referring to
missing `defs' or `defs.in', since that variable is now defined
before those checks.

diff --git a/tests/defs.in b/tests/defs.in
--- a/tests/defs.in
+++ b/tests/defs.in
@@ -114,13 +114,13 @@ PATH="`pwd`$PATH_SEPARATOR$PATH"; export PATH
 
 # Ensure we are running from the right directory.
 test -f ./defs || {
-   echo "./defs: not found in current directory" >&2
+   echo "$me: ./defs: not found in current directory" >&2
    exit 1
 }
 
 # Ensure $testsrcdir is set correctly.
 test -f "$testsrcdir/defs.in" || {
-   echo "$testsrcdir/defs.in not found, check \$testsrcdir" >&2
+   echo "$me: $testsrcdir/defs.in not found, check \$testsrcdir" >&2
    exit 1
 }
 
