tests: fix spurious failures in self tests
Our ad-hoc usage of `tests/defs' in the testsuite's self tests
stopped working properly when we made the test scripts re-execute
themselves with the configure-time $SHELL.  Fix this.

Fixes a bug introduced by commit 'v1.11-874-g1321be7'.

* tests/defs: Only check that we can find the client test script
when we must re-execute it.
* tests/self-check-cleanup.test: Export `AM_TESTS_REEXEC' to "no"
before running the self tests.
* tests/self-check-dir.test: Likewise.
* tests/self-check-explicit-skips.test: Likewise.
* tests/self-check-me.test: Likewise.
* tests/self-check-sanity.test: Likewise.
* tests/self-check-reexec.test: New test.
* tests/Makefile.am (TESTS): Update.

diff --git a/tests/defs b/tests/defs
--- a/tests/defs
+++ b/tests/defs
@@ -76,12 +76,6 @@ test -f "$testbuilddir/defs-static" || {
    exit 99
 }
 
-# Ensure we can find ourselves.
-test -f "$0" || {
-   echo "$me: unable to find myself: $0" >&2
-   exit 1
-}
-
 
 ## ------------------------------------ ##
 ##  Ensure we run with a proper shell.  ##
@@ -93,6 +87,11 @@ case ${AM_TESTS_REEXEC-yes} in
   n|no|false|0)
     ;;
   *)
+    # Ensure we can find ourselves.
+    if test ! -f "$0"; then
+      echo "$me: unable to find myself: $0" >&2
+      exit 99
+    fi
     AM_TESTS_REEXEC=no; export AM_TESTS_REEXEC
     # Cannot simply do `opts=$-', since the content of $- is not
     # portable among different shells.  So try to propagate only
