tests: work around Tru64 sh -e issues for instspc*.test.
Apparently, Tru64 sh does not like turning off errexit mode,
and gets confused.

* tests/defs: Document 'errexit' cleanliness requirement.
* tests/defs-static.in: Likewise.  Avoid error from command
substitution to abort instspc*.test with Tru64/OSF 5.1 sh.
* tests/instspc-tests.sh: Drop now-unneeded temporary errexit
dropping.  Add strategic '|| Exit' to let tests work on Tru64.

Signed-off-by: Ralf Wildenhues <Ralf.Wildenhues@gmx.de>

diff --git a/tests/defs-static.in b/tests/defs-static.in
--- a/tests/defs-static.in
+++ b/tests/defs-static.in
@@ -2,7 +2,8 @@
 # @configure_input@
 #
 # Copyright (C) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
-# 2005, 2006, 2007, 2008, 2009, 2010 Free Software Foundation, Inc.
+# 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software Foundation,
+# Inc.
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,7 +19,8 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 # Defines and minimal setup for Automake testing environment.
-# IMPORTANT: Multiple inclusions of this file should be idempotent!
+# Multiple inclusions of this file should be idempotent!
+# This code needs to be 'set -e' clean.
 
 # Be more Bourne compatible.
 # (Snippet inspired to configure's initialization in Autoconf 2.64)
@@ -57,7 +59,8 @@ if test -n "${ZSH_VERSION+set}" && (emulate sh) >/dev/null 2>&1; then
   fi
 else
   argv0=$0
-  case `(set -o) 2>/dev/null` in *posix*) set -o posix;; esac
+  # Avoid command substitution failure, for Tru64 sh -e and instspc*.test.
+  case `(set -o) 2>/dev/null || :` in *posix*) set -o posix;; esac
 fi
 
 testsrcdir='@abs_srcdir@'
