* tests/defs.in: Run $MAKE --version -v. * tests/dollar.test: Abort on ./defs failure. * tests/lex5.test: Require GNUmake, not make.

diff --git a/tests/defs.in b/tests/defs.in
--- a/tests/defs.in
+++ b/tests/defs.in
@@ -72,8 +72,9 @@ then
 	( bison --version ) || exit 77
 	;;
       GNUmake)
-	echo "$me: running $MAKE --version"
-	( $MAKE --version ) || exit 77
+	# Use --version and -v, because SGI Make doesn't fail on --version.
+	echo "$me: running $MAKE --version -v"
+	( $MAKE --version -v ) || exit 77
 	;;
       gcc)
         # When gcc is required, export `CC=gcc' so that ./configure
