tests: quote 'like this', not `like this', as per GCS recommendation
This patch converts the automake testsuite and related files, to
the use of new quoting format 'like this' or "like this" rather
than `like this'.

This is done for consistency with the new recommendations in the GNU
Coding Standards, and, well, because I've come to actually prefer
the '...' and "..." quoting formats over the `...' one.

* tests/README: Update quoting format throughout.  Remove some
"excessive" use of quoting, and throw in minor rewording where
appropriate.
* tests/Makefile.am: Likewise, for comments.
* tests/CheckListOfTests.am: Likewise.
* tests/defs-static.in: Likewise.
* tests/defs: Likewise.
* tests/trivial-test-driver: Likewise.
* Many tests/*.tap, tests/*.test and tests/*.sh files: Likewise,
and for the diagnostic and informational messages as well.
* tests/gen-testsuite-part: Likewise, and for the generated tests
as well.

diff --git a/tests/defs b/tests/defs
--- a/tests/defs
+++ b/tests/defs
@@ -39,7 +39,7 @@ test -f ./defs-static || {
 # Enable the errexit shell flag early.
 set -e
 
-# The name of the current test (without the `.test' suffix).
+# The name of the current test (without the '.test' suffix).
 # Test scripts can override it if they need to (but this should
 # be done carefully, and *before* including ./defs).
 if test -z "$me"; then
@@ -94,7 +94,7 @@ case ${AM_TESTS_REEXEC-yes} in
       exit 99
     fi
     AM_TESTS_REEXEC=no; export AM_TESTS_REEXEC
-    # Cannot simply do `opts=$-', since the content of $- is not
+    # Cannot simply do "opts=$-", since the content of $- is not
     # portable among different shells.  So try to propagate only
     # the portable and interesting options.
     case $- in
@@ -142,7 +142,7 @@ unset __MKLVL__ MAKE_JOBS_FIFO                     # For BSD make.
 unset DMAKE_CHILD DMAKE_DEF_PRINTED DMAKE_MAX_JOBS # For Solaris dmake.
 # Unset verbosity flag.
 unset V
-# Also unset variables that will let `make -e install' divert
+# Also unset variables that will let "make -e install" divert
 # files into unwanted directories.
 unset DESTDIR
 unset prefix exec_prefix bindir datarootdir datadir docdir dvidir
@@ -150,7 +150,7 @@ unset htmldir includedir infodir libdir libexecdir localedir mandir
 unset oldincludedir pdfdir psdir sbindir sharedstatedir sysconfdir
 # Unset variables that might change the "make distcheck" behaviour.
 unset DISTCHECK_CONFIGURE_FLAGS AM_DISTCHECK_CONFIGURE_FLAGS
-# The tests call `make -e' but we do not want $srcdir from the environment
+# The tests call "make -e" but we do not want $srcdir from the environment
 # to override the definition from the Makefile.
 unset srcdir
 # Also unset variables that control our test driver.  While not
@@ -194,13 +194,13 @@ am_keeping_testdirs ()
   esac
 }
 
-# This is used in `Exit' and in the exit trap.  See comments in the latter
+# This is used in 'Exit' and in the exit trap.  See comments in the latter
 # for more information,
 am__test_skipped=no
 
 # We use a trap below for cleanup.  This requires us to go through
 # hoops to get the right exit status transported through the signal.
-# So use `Exit STATUS' instead of `exit STATUS' inside of the tests.
+# So use "Exit STATUS" instead of "exit STATUS" inside of the tests.
 # Turn off errexit here so that we don't trip the bug with OSF1/Tru64
 # sh inside this function.
 Exit ()
@@ -321,7 +321,7 @@ AUTOMAKE_run ()
 
 # AUTOMAKE_fails [-d DESCRIPTION] [OPTIONS...]
 # --------------------------------------------
-# Run automake with OPTIONS, and fail if doesn't exit with status `1'.
+# Run automake with OPTIONS, and fail if doesn't exit with status 1.
 # Should be polymorphic for TAP and "plain" tests.  The DESCRIPTION,
 # when provided, is used for console reporting, only if the TAP
 # protocol is in use in the current test script.
@@ -332,7 +332,7 @@ AUTOMAKE_fails ()
 
 # extract_configure_help { --OPTION | VARIABLE-NAME } [FILES]
 # -----------------------------------------------------------
-# Use this to extract from the output of `./configure --help' (or similar)
+# Use this to extract from the output of "./configure --help" (or similar)
 # the description or help message associated to the given --OPTION or
 # VARIABLE-NAME.
 extract_configure_help ()
@@ -365,7 +365,7 @@ extract_configure_help ()
 
 # grep_configure_help { --OPTION | VARIABLE-NAME } REGEXP
 # -------------------------------------------------------
-# Grep the section of `./configure --help' output associated with either
+# Grep the section of "./configure --help" output associated with either
 # --OPTION or VARIABLE-NAME for the given *extended* regular expression.
 grep_configure_help ()
 {
@@ -392,7 +392,7 @@ using_gmake ()
     '')
       # Use --version AND -v, because SGI Make doesn't fail on --version.
       # Also grep for GNU because newer versions of FreeBSD make do
-      # not complain about `--version' (they seem to silently ignore it).
+      # not complain about --version (they seem to silently ignore it).
       if $MAKE --version -v | grep GNU; then
         am__using_gmake=yes
         return 0
@@ -542,8 +542,8 @@ rm_rf_ ()
 # Check that a testsuite run driven by the parallel-tests harness has
 # had the specified numbers of test results (specified by kind).
 # This function assumes that the output of "make check" or "make recheck"
-# has been saved in the `stdout' file in the current directory, and its
-# log in the `test-suite.log' file.
+# has been saved in the 'stdout' file in the current directory, and its
+# log in the 'test-suite.log' file.
 count_test_results ()
 {
   # Use a subshell so that we won't pollute the script namespace.
@@ -555,7 +555,7 @@ count_test_results ()
     $EGREP -i '(total|x?pass|x?fail|skip|error)' stdout || :
     rc=0
     # Avoid spurious failures with shells with "overly sensible"
-    # `errexit' shell flag, such as e.g., Solaris /bin/sh.
+    # errexit shell flag, such as e.g., Solaris /bin/sh.
     set +e
     test `grep -c '^PASS:'  stdout` -eq $pass  || rc=1
     test `grep -c '^XFAIL:' stdout` -eq $xfail || rc=1
@@ -606,8 +606,8 @@ sed_unindent_prog="" # Avoid interferences from the environment.
 
 # get_shell_script SCRIPT-NAME
 # -----------------------------
-# Fetch an Automake-provided shell script from the `lib/' directory into
-# the current directory, and, if the `$am_test_prefer_config_shell'
+# Fetch an Automake-provided shell script from the 'lib/' directory into
+# the current directory, and, if the '$am_test_prefer_config_shell'
 # variable is set to "yes", modify its shebang line to use $SHELL instead
 # of /bin/sh.
 get_shell_script ()
@@ -643,7 +643,7 @@ xsi_shell_code='
 
 # fetch_tap_driver
 # ----------------
-# Fetch the Automake-provided TAP driver from the `lib/' directory into
+# Fetch the Automake-provided TAP driver from the 'lib/' directory into
 # the current directory, and edit its shebang line so that it will be
 # run with the perl interpreter determined at configure time.
 fetch_tap_driver ()
@@ -757,23 +757,23 @@ do
       # Do not use --version, bzip2 still tries to compress stdin.
       echo "$me: running bzip2 --help"
       bzip2 --help \
-        || skip_all_ "required program \`bzip2' not available"
+        || skip_all_ "required program 'bzip2' not available"
       ;;
     cl)
       CC=cl
       # Don't export CFLAGS, as that could have been initialized to only
       # work with the C compiler detected at configure time.  If the user
-      # wants CFLAGS to also influence `cl', he can still export CFLAGS
+      # wants CFLAGS to also influence 'cl', he can still export CFLAGS
       # in the environment "by hand" before calling the testsuite.
       export CC CPPFLAGS
       echo "$me: running $CC -?"
-      $CC -? || skip_all_ "Microsoft C compiler \`$CC' not available"
+      $CC -? || skip_all_ "Microsoft C compiler '$CC' not available"
       ;;
     cscope)
       # Sun cscope is interactive without redirection.
       echo "$me: running cscope --version </dev/null"
       cscope --version </dev/null \
-        || skip_all_ "required program \`cscope' not available"
+        || skip_all_ "required program 'cscope' not available"
       ;;
     cygpath)
       echo "$me: running cygpath --version"
@@ -786,7 +786,7 @@ do
       # to make sure we do not pollute the tests/ directory.
       echo "$me: running etags --version -o /dev/null"
       etags --version -o /dev/null \
-        || skip_all_ "required program \`etags' not available"
+        || skip_all_ "required program 'etags' not available"
       ;;
     GNUmake)
       for make_ in "$MAKE" gmake gnumake :; do
@@ -803,7 +803,7 @@ do
       unset make_
       ;;
     gcc)
-      # When gcc is required, export `CC=gcc' so that ./configure
+      # When gcc is required, export "CC=gcc" so that ./configure
       # always use it.  This is important only when the user
       # has defined CC in his environment, otherwise ./configure will
       # prefer gcc to other compilers.
@@ -860,14 +860,14 @@ do
       ;;
     javac)
       # The Java compiler from JDK 1.5 (and presumably earlier versions)
-      # cannot handle the `-version' option by itself: it bails out
-      # telling that source files are missing.  Adding also the `-help'
+      # cannot handle the '-version' option by itself: it bails out
+      # telling that source files are missing.  Adding also the '-help'
       # option seems to solve the problem.
       echo "$me: running javac -version -help"
       javac -version -help || skip_all_ "Sun Java compiler not available"
       ;;
     java)
-      # See the comments above about `javac' for why we use also `-help'.
+      # See the comments above about 'javac' for why we use also '-help'.
       echo "$me: running java -version -help"
       java -version -help || skip_all_ "Sun Java interpreter not found"
       ;;
@@ -878,19 +878,19 @@ do
       # create the archive, but lib will output its version.
       echo "$me: running $AR -out:defstest.lib"
       $AR -out:defstest.lib \
-        || skip_all_ "Microsoft \`lib' utility not available"
+        || skip_all_ "Microsoft 'lib' utility not available"
       ;;
     makedepend)
       echo "$me: running makedepend -f-"
       makedepend -f- \
-        || skip_all_ "required program \`makedepend' not available"
+        || skip_all_ "required program 'makedepend' not available"
       ;;
     makeinfo-html)
-      # Make sure we have makeinfo, and it understands `--html'.
+      # Make sure we have makeinfo, and it understands '--html'.
       echo "$me: running makeinfo --html --version"
       makeinfo --html --version \
         || skip_all_ "cannot find a makeinfo program that groks the" \
-                 "\`--html' option"
+                 "\'--html' option"
       ;;
     mingw)
       uname_s=`uname -s || echo UNKNOWN`
@@ -959,17 +959,17 @@ do
         || skip_all_ "DejaGnu is not available"
       ;;
     tex)
-      # No all versions of Tex support `--version', so we use
+      # No all versions of Tex support '--version', so we use
       # a configure check.
       if test -z "$TEX"; then
         skip_all_ "TeX is required, but it wasn't found by configure"
       fi
       ;;
     texi2dvi-o)
-      # Texi2dvi supports `-o' since Texinfo 4.1.
+      # Texi2dvi supports '-o' since Texinfo 4.1.
       echo "$me: running texi2dvi -o /dev/null --version"
       texi2dvi -o /dev/null --version \
-        || skip_all_ "required program \`texi2dvi' not available"
+        || skip_all_ "required program 'texi2dvi' not available"
       ;;
     lex)
       test x"$LEX" = x"false" && skip_all_ "lex not found or disabled"
@@ -982,12 +982,12 @@ do
     flex)
       LEX=flex; export LEX
       echo "$me: running flex --version"
-      flex --version || skip_all_ "required program \`flex' not available"
+      flex --version || skip_all_ "required program 'flex' not available"
       ;;
     bison)
       YACC='bison -y'; export YACC
       echo "$me: running bison --version"
-      bison --version || skip_all_ "required program \`bison' not available"
+      bison --version || skip_all_ "required program 'bison' not available"
       ;;
     *)
       # Generic case: the tool must support --version.
@@ -995,12 +995,12 @@ do
       # It is not likely but possible that $tool is a special builtin,
       # in which case the shell is allowed to exit after an error.
       # So, please leave the subshell here.
-      ($tool --version) || skip_all_ "required program \`$tool' not available"
+      ($tool --version) || skip_all_ "required program '$tool' not available"
       ;;
   esac
 done
 
-# Using just `$testbuilddir' for the check here is ok, since the
+# Using just $testbuilddir for the check here is ok, since the
 # further temporary subdirectory where the test will be run is
 # ensured not to contain any whitespace character.
 case $testbuilddir in
@@ -1091,7 +1091,7 @@ if test "$sh_errexit_works" = yes; then
   trap "fatal_ 'caught signal SIGQUIT'" 3
   # Ignore further SIGPIPE in the trap code.  This is required to avoid
   # a very weird issue with some shells, at least when the execution of
-  # the automake testsuite is driven by the `prove' utility: if prove
+  # the automake testsuite is driven by the 'prove' utility: if prove
   # (or the make process that has spawned it) gets interrupted with
   # Ctrl-C, the shell might go in a loop, continually getting a SIGPIPE,
   # sometimes finally dumping core, other times hanging indefinitely.
diff --git a/tests/defs-static.in b/tests/defs-static.in
--- a/tests/defs-static.in
+++ b/tests/defs-static.in
@@ -35,8 +35,8 @@ if test -n "${ZSH_VERSION+set}" && (emulate sh) >/dev/null 2>&1; then
   alias -g '${1+"$@"}'='"$@"'
   setopt NO_GLOB_SUBST
   # If Zsh is not started directly in Bourne-compatibility mode, it has
-  # some incompatibilities in the handling of `$0' that conflict with
-  # our usage: i.e., `$0' inside a file sourced with the `.' builtin is
+  # some incompatibilities in the handling of $0 that conflict with
+  # our usage: i.e., $0 inside a file sourced with the '.' builtin is
   # temporarily set to the name of the sourced file.
   # Work around this when possible, otherwise abort the script.
   # Note that a bug in some versions of Zsh prevents us from resetting $0
@@ -80,7 +80,7 @@ for var in \
   am_original_ACLOCAL \
 ; do
   if eval "test x\"\$$var\" != x" && env | grep "^$var=" >/dev/null; then
-    echo "$argv0: variable \`$var' is set in the environment:" \
+    echo "$argv0: variable '$var' is set in the environment:" \
          "this is unsafe" >&2
     exit 99
   fi
@@ -123,8 +123,8 @@ case ${am_running_installcheck:=no} in
     am_system_acdir=$top_testsrcdir/m4/acdir
     ;;
   *)
-    echo "$argv0: variable \`am_running_installcheck' has invalid"
-         "value \`$am_running_installcheck'" >&2
+    echo "$argv0: variable 'am_running_installcheck' has invalid"
+         "value '$am_running_installcheck'" >&2
     exit 99
     ;;
 esac
@@ -154,7 +154,7 @@ AUTOUPDATE=${AM_TESTSUITE_AUTOUPDATE-${AUTOUPDATE-'@am_AUTOUPDATE@'}}
 
 # Tests who want complete control over aclocal or automake command-line
 # options should use $am_original_ACLOCAL or $am_original_AUTOMAKE.  The
-# `test -z' tests take care not to re-initialize them if defs-static
+# "test -z" tests take care not to re-initialize them if defs-static
 # is re-sourced, as we want defs-static to remain really idempotent.
 if test -z "$am_original_AUTOMAKE"; then
   am_original_AUTOMAKE=${AM_TESTSUITE_AUTOMAKE-${AUTOMAKE-"automake-$APIVERSION"}}
@@ -202,7 +202,7 @@ GNU_FCFLAGS=${AM_TESTSUITE_GNU_FCFLAGS-${GNU_FCFLAGS-'@GNU_FCFLAGS@'}}
 GNU_CXXFLAGS=${AM_TESTSUITE_GNU_CXXFLAGS-${GNU_CXXFLAGS-'@GNU_CXXFLAGS@'}}
 GNU_CFLAGS=${AM_TESTSUITE_GNU_CFLAGS-${GNU_CFLAGS-'@GNU_CFLAGS@'}}
 
-# No all versions of Tex support `--version', so we use a configure
+# No all versions of Tex support '--version', so we use a configure
 # check to decide if tex is available.  This decision is embodied in
 # this variable.
 TEX=${AM_TESTSUITE_TEX-'@TEX@'}
