* lib/missing (makeinfo): If makeinfo exists, and we're in --run 	mode, then simply fail.

diff --git a/lib/missing b/lib/missing
--- a/lib/missing
+++ b/lib/missing
@@ -209,6 +209,11 @@ WARNING: \`$1' is missing on your system.  You should only need it if
     ;;
 
   makeinfo)
+    if test -z "$run" && sh -c 'makeinfo --version > /dev/null 2>&1'; then
+       # We have makeinfo, but it failed.
+       exit 1
+    fi
+
     echo 1>&2 "\
 WARNING: \`$1' is missing on your system.  You should only need it if
          you modified a \`.texi' or \`.texinfo' file, or any other file
