ylwrap: warn when expected output files are missing
* lib/ylwrap (handle_renaming): Warn if an expected output file
from the wrapped program is missing, instead of just erroring out
silently.
* tests/ylwrap-fail.test: Extend.

diff --git a/lib/ylwrap b/lib/ylwrap
--- a/lib/ylwrap
+++ b/lib/ylwrap
@@ -142,7 +142,10 @@ handle_renaming ()
       # used, we don't want an error when the `y.output' file is "missing".
       case $wrapped:$ofrom in
         yacc:y.tab.h|yacc:y.output) ;;
-        *) ret=1;;
+        *)
+          echo "ylwrap: expected file \`$from' not found" >&2
+          ret=1
+          ;;
       esac
     fi
 }
